spring.application.name=techlog

spring.config.import=application-private.properties


# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/lectureReserve?serverTimezone=UTC&characterEncoding=UTF-8
spring.datasource.username=${MYSQL_ID}
spring.datasource.password=${MYSQL_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true